# Common configuration
service: task0
frameworkVersion: ">=1.36.3 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**

# Serverless functions configuration
functions:
