service: task1
frameworkVersion: ">=1.36.3 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: eu-central-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - serverless_functions/**
  exclude:
    - monolith/**

functions:
  hello1:
    handler: serverless_functions/handler1.hello
    events:
      - http:
          path: hello1
          method: get
  hello2:
    handler: serverless_functions/handler2.hello
    events:
      - http:
          path: hello2
          method: get
  hello3:
    handler: serverless_functions/handler3.hello
    events:
      - http:
          path: hello3
          method: get
  hello4:
    handler: serverless_functions/handler4.hello
    events:
      - http:
          path: hello4
          method: get

