# Common configuration
service: task3
frameworkVersion: ">=1.36.3 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: production
  region: eu-central-1
  environment:
    GROUP_ID: ${env:GROUP_ID}
    ELASTIC_URL: http://${env:ELASTIC_IP}:9200/myindex/mydoc

package:
  include:
    - serverless_functions/**
  exclude:
    - hint/**

# Serverless functions configuration
functions:

  temperature:
    handler: serverless_functions/temperature.temperature
    events:
      - http:
          path: temperature
          method: get
    environment:
      FUNCTION_ID: 3
