service: task3
frameworkVersion: ">=1.36.3 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - ../code/serverless_functions/**

functions:
  temperature:
    handler: serverless_functions/temperature.retrieve_temperature
    events:
      - http:
          path: temperature
          method: get
