service: task2
frameworkVersion: "=1.36.3"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - ../code/serverless_functions/**
  exclude:
    - ../code/monolith/**


functions:
  hello1:
    handler: serverless_functions/handler1.hello
    events:
      - http:
          path: hello1/{foo}
          method: post
          request:
            parameters:
              paths:
                foo: true
              queries:
                bar: true
  hello2:
    handler: serverless_functions/handler2.hello
    events:
      - http:
          path: hello2
          method: get
  hello3:
    handler: serverless_functions/handler3.hello
    events:
      - http:
          path: hello3
          method: get
  hello4:
    handler: serverless_functions/handler4.hello
    events:
      - http:
          path: hello4
          method: get
  hello5:
    handler: serverless_functions/handler5.hello
    events:
      - http:
          path: hello5
          method: get

