# Common configuration
service: task2

provider:
  name: aws
  iamRoleStatements: []
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  runtime: python3.7
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**
  exclude:
    - monolith/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

# Serverless functions configuration
functions:
