# Common configuration
service: task2

provider:
  name: aws
  iamRoleStatements: []
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  runtime: python3.6
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

# Serverless functions configuration
functions:
