# Common configuration
service: task2

provider:
  name: aws
  iamRoleStatements: []
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  runtime: python3.6
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

# Serverless functions configuration
functions:
  upload_form:
    handler: serverless_functions/image.get_upload_form
    events:
      - http:
          path: image/upload_form
          method: get

