# Common configuration
service: task1

provider:
  name: aws
  iamRoleStatements: []
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: "arn:aws:s3:::my-bucket-name"
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#        - "s3:GetObject"
#        - "s3:DeleteObject"
#      Resource: "arn:aws:s3:::my-bucket-name/*"
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  runtime: python3.6
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

# Serverless functions configuration
functions:
  upload_form:
    handler: serverless_functions/image.get_upload_form
    events:
      - http:
          path: upload_form
          method: get

